-- ============================================================
-- bdfacturas_postgres_normalizada — versión normalizada (3FN)
-- Diseño de Software
--
-- Equivalente a bdfacturas_postgres.sql, pero:
--   * SIN triggers y SIN procedimientos almacenados: la lógica de
--     negocio (descontar stock, validar mínimo de productos, anular)
--     vive en la aplicación, dentro de una transacción.
--   * SIN datos derivados guardados:
--       - factura.total               → se calcula (vista vw_factura)
--       - productosporfactura.subtotal → se calcula (vista vw_productosporfactura)
--     En su lugar, cada línea guarda el valorunitario CON EL QUE SE
--     VENDIÓ (dato histórico, no derivable: el precio del producto
--     puede cambiar después).
--   * El estado de la factura deja de ser texto libre y pasa a una
--     tabla de catálogo (estado_factura).
--   * Restricciones explícitas: UNIQUE en claves alternas, CHECK en
--     cantidades y valores, precisión en los NUMERIC.
--
-- Los nombres de tablas y columnas se conservan respecto al script
-- original, para que el código existente (p. ej. la tabla producto
-- de la v1) siga funcionando.
-- ============================================================

-- ============================================================
-- TABLAS INDEPENDIENTES (sin foreign keys)
-- ============================================================

CREATE TABLE empresa (
    codigo VARCHAR(10)  NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    CONSTRAINT pk_empresa PRIMARY KEY (codigo),
    CONSTRAINT uq_empresa_nombre UNIQUE (nombre)
);

CREATE TABLE persona (
    codigo   VARCHAR(10)  NOT NULL,
    nombre   VARCHAR(100) NOT NULL,
    email    VARCHAR(100) NOT NULL,
    telefono VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_persona PRIMARY KEY (codigo),
    CONSTRAINT uq_persona_email UNIQUE (email)
);

CREATE TABLE producto (
    codigo        VARCHAR(10)   NOT NULL,
    nombre        VARCHAR(100)  NOT NULL,
    stock         INTEGER       NOT NULL,
    valorunitario NUMERIC(14,2) NOT NULL,
    CONSTRAINT pk_producto PRIMARY KEY (codigo),
    CONSTRAINT ck_producto_stock CHECK (stock >= 0),
    CONSTRAINT ck_producto_valorunitario CHECK (valorunitario >= 0)
);

CREATE TABLE estado_factura (
    id     SMALLINT    NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    CONSTRAINT pk_estado_factura PRIMARY KEY (id),
    CONSTRAINT uq_estado_factura_nombre UNIQUE (nombre)
);

CREATE TABLE rol (
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT pk_rol PRIMARY KEY (id),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre)
);

CREATE TABLE ruta (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    ruta        VARCHAR(100) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    CONSTRAINT pk_ruta PRIMARY KEY (id),
    CONSTRAINT uq_ruta UNIQUE (ruta)
);

CREATE TABLE usuario (
    email      VARCHAR(100) NOT NULL,
    contrasena VARCHAR(200) NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (email)
);

-- ============================================================
-- TABLAS DEPENDIENTES (con foreign keys)
-- ============================================================

-- cliente y vendedor son ROLES de una persona: una persona es, como
-- mucho, un cliente y un vendedor (UNIQUE en fkcodpersona).
CREATE TABLE cliente (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    credito      NUMERIC(14,2) NOT NULL DEFAULT 0,
    fkcodpersona VARCHAR(10)   NOT NULL,
    fkcodempresa VARCHAR(10),
    CONSTRAINT pk_cliente PRIMARY KEY (id),
    CONSTRAINT uq_cliente_persona UNIQUE (fkcodpersona),
    CONSTRAINT ck_cliente_credito CHECK (credito >= 0),
    CONSTRAINT fk_cliente_persona FOREIGN KEY (fkcodpersona) REFERENCES persona(codigo),
    CONSTRAINT fk_cliente_empresa FOREIGN KEY (fkcodempresa) REFERENCES empresa(codigo)
);

CREATE TABLE vendedor (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY,
    carnet       INTEGER      NOT NULL,
    direccion    VARCHAR(100) NOT NULL,
    fkcodpersona VARCHAR(10)  NOT NULL,
    CONSTRAINT pk_vendedor PRIMARY KEY (id),
    CONSTRAINT uq_vendedor_carnet UNIQUE (carnet),
    CONSTRAINT uq_vendedor_persona UNIQUE (fkcodpersona),
    CONSTRAINT fk_vendedor_persona FOREIGN KEY (fkcodpersona) REFERENCES persona(codigo)
);

-- Sin columna total: el total es la suma de sus líneas (vw_factura).
CREATE TABLE factura (
    numero       INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fkidestado   SMALLINT  NOT NULL DEFAULT 1,
    fkidcliente  INTEGER   NOT NULL,
    fkidvendedor INTEGER   NOT NULL,
    CONSTRAINT pk_factura PRIMARY KEY (numero),
    CONSTRAINT fk_factura_estado FOREIGN KEY (fkidestado) REFERENCES estado_factura(id),
    CONSTRAINT fk_factura_cliente FOREIGN KEY (fkidcliente) REFERENCES cliente(id),
    CONSTRAINT fk_factura_vendedor FOREIGN KEY (fkidvendedor) REFERENCES vendedor(id)
);

-- Sin columna subtotal: subtotal = cantidad * valorunitario
-- (vw_productosporfactura). valorunitario es el precio de la venta.
CREATE TABLE productosporfactura (
    fknumfactura  INTEGER       NOT NULL,
    fkcodproducto VARCHAR(10)   NOT NULL,
    cantidad      INTEGER       NOT NULL,
    valorunitario NUMERIC(14,2) NOT NULL,
    CONSTRAINT pk_productosporfactura PRIMARY KEY (fknumfactura, fkcodproducto),
    CONSTRAINT ck_prodfact_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_prodfact_valorunitario CHECK (valorunitario >= 0),
    CONSTRAINT fk_prodfact_factura FOREIGN KEY (fknumfactura) REFERENCES factura(numero) ON DELETE CASCADE,
    CONSTRAINT fk_prodfact_producto FOREIGN KEY (fkcodproducto) REFERENCES producto(codigo)
);

CREATE TABLE rol_usuario (
    fkemail VARCHAR(100) NOT NULL,
    fkidrol INTEGER      NOT NULL,
    CONSTRAINT pk_rol_usuario PRIMARY KEY (fkemail, fkidrol),
    CONSTRAINT fk_rolusuario_usuario FOREIGN KEY (fkemail) REFERENCES usuario(email) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_rolusuario_rol FOREIGN KEY (fkidrol) REFERENCES rol(id) ON DELETE CASCADE
);

CREATE TABLE rutarol (
    fkidruta INTEGER NOT NULL,
    fkidrol  INTEGER NOT NULL,
    CONSTRAINT pk_rutarol PRIMARY KEY (fkidruta, fkidrol),
    CONSTRAINT fk_rutarol_ruta FOREIGN KEY (fkidruta) REFERENCES ruta(id) ON DELETE CASCADE,
    CONSTRAINT fk_rutarol_rol FOREIGN KEY (fkidrol) REFERENCES rol(id) ON DELETE CASCADE
);

-- ============================================================
-- VISTAS (los datos derivados se calculan, no se guardan)
-- ============================================================

CREATE VIEW vw_productosporfactura AS
SELECT pf.fknumfactura,
       pf.fkcodproducto,
       pf.cantidad,
       pf.valorunitario,
       pf.cantidad * pf.valorunitario AS subtotal
FROM productosporfactura pf;

CREATE VIEW vw_factura AS
SELECT f.numero,
       f.fecha,
       ef.nombre AS estado,
       f.fkidcliente,
       f.fkidvendedor,
       COALESCE(SUM(pf.cantidad * pf.valorunitario), 0) AS total
FROM factura f
JOIN estado_factura ef ON ef.id = f.fkidestado
LEFT JOIN productosporfactura pf ON pf.fknumfactura = f.numero
GROUP BY f.numero, f.fecha, ef.nombre, f.fkidcliente, f.fkidvendedor;

-- ============================================================
-- DATOS
-- ============================================================

-- Empresas
INSERT INTO empresa (codigo, nombre) VALUES
('E001', 'Comercial Los Andes S.A.'),
('E002', 'Distribuciones El Centro S.A.'),
('E999', 'Empresa Test');

-- Personas
INSERT INTO persona (codigo, nombre, email, telefono) VALUES
('P001', 'Ana Torres', 'ana.torres@correo.com', '3011111111'),
('P002', 'Carlos Pérez', 'carlos.perez@correo.com', '3022222222'),
('P003', 'María Gómez', 'maria.gomez@correo.com', '3033333333'),
('P004', 'Juan Díaz', 'juan.diaz@correo.com', '3044444444'),
('P005', 'Laura Rojas', 'laura.rojas@correo.com', '3055555555'),
('P006', 'Pedro Castillo', 'pedro.castillo@correo.com', '3066666666');

-- Productos (stock ya descontado por las facturas semilla)
INSERT INTO producto (codigo, nombre, stock, valorunitario) VALUES
('PR001', 'Laptop Lenovo IdeaPad', 17, 2500000),
('PR002', 'Monitor Samsung 24"', 27, 800000),
('PR003', 'Teclado Logitech K380', 42, 150000),
('PR004', 'Mouse HP', 55, 90000),
('PR005', 'Impresora Epson EcoTank1', 14, 1100000),
('PR006', 'Auriculares Sony WH-CH510', 23, 240000),
('PR007', 'Tablet Samsung Tab A9', 15, 950000),
('PR008', 'Disco Duro Seagate 1TB', 32, 280000);

-- Estados de factura
INSERT INTO estado_factura (id, nombre) VALUES
(1, 'activa'),
(2, 'anulada');

-- Roles
INSERT INTO rol (id, nombre) VALUES
(1, 'Administrador'),
(2, 'Vendedor'),
(3, 'Cajero'),
(4, 'Contador'),
(5, 'Cliente');

-- Rutas
INSERT INTO ruta (id, ruta, descripcion) VALUES
(1,  '/home', 'Página principal - Dashboard'),
(2,  '/usuario', 'Gestión de usuarios'),
(3,  '/factura', 'Gestión de facturas'),
(4,  '/cliente', 'Gestión de clientes'),
(5,  '/vendedor', 'Gestión de vendedores'),
(6,  '/persona', 'Gestión de personas'),
(7,  '/empresa', 'Gestión de empresas'),
(8,  '/producto', 'Gestión de productos'),
(9,  '/rol', 'Gestión de roles'),
(10, '/permiso', 'Gestión de permisos (asignación rol-ruta)'),
(11, '/permiso/crear', 'Crear permiso (POST)'),
(12, '/permiso/eliminar', 'Eliminar permiso (POST)'),
(13, '/ruta', 'Gestión de rutas del sistema'),
(14, '/ruta/crear', 'Crear ruta (POST)'),
(15, '/ruta/eliminar', 'Eliminar ruta (POST)');

-- Usuarios
-- ============================================================
-- LAS CONTRASENAS ESTAN EN TEXTO PLANO, Y ES A PROPOSITO
--
-- Esto esta MAL, y esta mal a proposito. Conviene leer por que antes de
-- copiarlo a cualquier otro sitio.
--
-- EN ESTA VERSION NO HAY HASH. Ni en el csproj -no esta BCrypt- ni en una sola
-- linea de codigo. El hash de la contrasena es la primera de las tres cosas
-- que llega con LA VERSION 3, y ponerlo aqui seria anticipar: la constitucion
-- lo prohibe, y ademas le quitaria a la v3 su primera leccion. El estudiante
-- no veria POR QUE hay que arreglarlo si ya estuviera arreglado.
--
-- LO QUE LA v3 HACE CON ESTO:
--
--   * Vuelve a sembrar las ocho filas con BCRYPT COSTO 12, EN EL SCRIPT -no a
--     mano: el siguiente `docker compose down -v` volveria a sembrar-.
--   * Deja las contrasenas en claro escritas en su 7_quickstart.md, porque del
--     hash NO SE PUEDE volver a la clave y sin saberlas no hay forma de
--     iniciar sesion.
--
-- Y la columna ya esta lista: es VARCHAR(200) y no 20, porque un hash de
-- bcrypt ocupa 60 caracteres.
--
-- LO QUE SI ESTA BIEN DESDE ESTA VERSION: la API nunca devuelve la contrasena.
-- El modelo `Usuario` tiene SOLO el email. Una respuesta no debe traer un
-- secreto que nadie pidio, y eso vale en cualquier version.
-- ============================================================
INSERT INTO usuario (email, contrasena) VALUES
('admin@correo.com', 'admin123'),
('vendedor1@correo.com', 'vendedor123'),
('jefe@correo.com', 'jefe123'),
('cliente1@correo.com', 'cliente123'),
('test_encript@correo.com', 'test123'),
('nuevo@correo.com', 'nuevo123'),
('carlos.castro@usbmed.edu.co', 'carlos123'),
('carloscastro5033@correo.itm.edu.co', 'carlos123');

-- Clientes
INSERT INTO cliente (id, credito, fkcodpersona, fkcodempresa) VALUES
(1, 520000, 'P001', 'E001'),
(2, 250000, 'P003', 'E002'),
(3, 400000, 'P005', 'E001'),
(5, 700000, 'P006', 'E001');

-- Vendedores
INSERT INTO vendedor (id, carnet, direccion, fkcodpersona) VALUES
(1, 1001, 'Calle 10 #5-33', 'P002'),
(2, 1002, 'Carrera 15 #7-20', 'P004'),
(3, 1003, 'Avenida 30 #18-09', 'P006');

-- Facturas (el total ya no se inserta: lo calcula vw_factura)
INSERT INTO factura (numero, fecha, fkidestado, fkidcliente, fkidvendedor) VALUES
(1, '2025-12-03 12:57:19.27592', 1, 1, 1),
(2, '2025-12-03 12:57:19.27592', 1, 2, 2),
(3, '2025-12-03 12:57:19.27592', 1, 3, 3),
(4, '2025-12-03 13:04:59.028613', 1, 1, 1),
(5, '2025-12-03 13:05:17.874385', 1, 2, 2),
(6, '2025-12-03 13:05:35.02846', 1, 3, 3);

-- Productos por factura (precio de venta en lugar de subtotal)
INSERT INTO productosporfactura (fknumfactura, fkcodproducto, cantidad, valorunitario) VALUES
(1, 'PR001', 2, 2500000),
(2, 'PR002', 1, 800000),
(2, 'PR003', 3, 150000),
(3, 'PR004', 5, 90000),
(3, 'PR005', 1, 1100000),
(3, 'PR006', 2, 240000),
(4, 'PR007', 1, 950000),
(5, 'PR007', 2, 950000),
(5, 'PR008', 3, 280000),
(6, 'PR001', 1, 2500000),
(6, 'PR002', 2, 800000),
(6, 'PR003', 5, 150000);

-- Roles por usuario
INSERT INTO rol_usuario (fkemail, fkidrol) VALUES
('admin@correo.com', 1),
('vendedor1@correo.com', 2),
('vendedor1@correo.com', 3),
('jefe@correo.com', 1),
('jefe@correo.com', 3),
('jefe@correo.com', 4),
('cliente1@correo.com', 5),
('test_encript@correo.com', 1),
('nuevo@correo.com', 1),
('nuevo@correo.com', 2),
('nuevo@correo.com', 3),
('carlos.castro@usbmed.edu.co', 1),
('carlos.castro@usbmed.edu.co', 2),
('carlos.castro@usbmed.edu.co', 3),
('carlos.castro@usbmed.edu.co', 4),
('carlos.castro@usbmed.edu.co', 5),
('carloscastro5033@correo.itm.edu.co', 1),
('carloscastro5033@correo.itm.edu.co', 2),
('carloscastro5033@correo.itm.edu.co', 3),
('carloscastro5033@correo.itm.edu.co', 4),
('carloscastro5033@correo.itm.edu.co', 5);

-- Rutas por rol (fkidruta, fkidrol)
-- Roles: 1=Administrador, 2=Vendedor, 3=Cajero, 4=Contador, 5=Cliente
INSERT INTO rutarol (fkidruta, fkidrol) VALUES
(1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1),
(1, 2), (3, 2), (4, 2),
(1, 3), (3, 3),
(1, 4), (4, 4), (8, 4),
(1, 5), (8, 5);

-- ============================================================
-- Sincronizar los contadores de identidad con los ids insertados
-- ============================================================
SELECT setval(pg_get_serial_sequence('rol', 'id'),          (SELECT MAX(id) FROM rol));
SELECT setval(pg_get_serial_sequence('ruta', 'id'),         (SELECT MAX(id) FROM ruta));
SELECT setval(pg_get_serial_sequence('cliente', 'id'),      (SELECT MAX(id) FROM cliente));
SELECT setval(pg_get_serial_sequence('vendedor', 'id'),     (SELECT MAX(id) FROM vendedor));
SELECT setval(pg_get_serial_sequence('factura', 'numero'),  (SELECT MAX(numero) FROM factura));
